### PR TITLE
Fix streamMessagesInternal with message attributes

### PR DESCRIPTION
**Pull request by meldmy**
Hi @sloshy - I found a bug in `streamMessagesWithAttributes`

### CODE REVIEW

**Comment by meldmy** [comment]
Hi @sloshy 🙂 Can you take a look at this fix, please? 🙏🏻

**Comment by meldmy** [comment]
Hi @sloshy  🙂 Can you take a look at this fix, please? 🙏🏻

**Comment by goboss** [comment]
I'd also like that fix to be merged :)

**Comment by meldmy** [comment]
Hi @sloshy 🙂  Can you take a look at this fix, please? 🙏🏻

**Comment by meldmy** [comment]
Hi @sloshy 🙂 Can you take a look at this MR, please? 🙏🏻

**Comment by meldmy** [comment]
@sloshy ping 📞 😉

**Review by sloshy — APPROVED** [review]
Very sorry for the long wait. I have been a little occupied recently and did not notice. Thank you so much! Release going out promptly.

**Comment by sloshy** [comment]
Released as part of v0.7.1, please allow some time for the release to go through. Thank you so much @meldmy. Feel free to also ping @mrerrormessage and/or @rn-ssteward in the future.

**Comment by sloshy** [comment]
Oh one more thing: my GitHub notifications are a little crazy these days, and I've been trying to minimize them as much as I can but if I'm not focused on something else the first thing I will check is usually my "Review Requested" notifications. So, if you ever make a new PR I will be much more likely to see it if you explicitly request my review. I do not remember seeing this in my review requests recently, so it might have slipped through the cracks, but if you use the review request feature I will try my best to get to it ASAP.

**Pull request merged**
